version: "3" 
services: 
   frontend: 
     image: zubairsource/mern_client 
     hostname: fe 
     networks:   
       - appnet 
  
  
   nodebackend:  
     image: zubairsource/mern_server 
     hostname: be 
     networks:   
       - appnet 
  
  
   reverseproxy:  
     image: zubairsource/mern_nginx 
     ports:  
       - "80:80" 
     depends_on: 
       - nodebackend 
       - frontend 
     networks:   
       - appnet 
  
networks: 
   appnet: