version: "3.8"
services:
  nginx:
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - client
      - api
    networks:
      - socialapp-network
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - MONGODB_URL=<mongo_url>
      - JWT_SECRET=sample
      - PORT=5000
    networks:
      - socialapp-network
    restart: always
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    networks:
      - socialapp-network
    restart: always

networks:
  socialapp-network:
    