version: "3.8"
services:
  nginx:
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - client
      - api
    networks:
      - socialapp-network
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - MONGO_URL='mongodb+srv://basit56700:BdulaAsitb56@cluster0.m0rnyrw.mongodb.net/?retryWrites=true&w=majority'
      - JWT_SECRET=sample
      - PORT=3001
    networks:
      - socialapp-network
    restart: always
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    networks:
      - socialapp-network
    restart: always

networks:
  socialapp-network:
    