version: "3.8"
services:
  nginx:
    restart: always
    container_name: nginx
    image: zubairsource/social-app-nginx:latest
    ports:
      - '80:80'
    depends_on:
      - client
      - api
    networks:
      - socialapp-network
  api:
    container_name: api
    image: zubairsource/social-app-backend:latest
    environment:
      - MONGO_URL='mongodb+srv://basit56700:BdulaAsitb56@cluster0.m0rnyrw.mongodb.net/?retryWrites=true&w=majority'
      - JWT_SECRET=sample
      - PORT=3001
    networks:
      - socialapp-network
    restart: always
  client:
    container_name: client
    image: zubairsource/social-app-frontend:latest
    networks:
      - socialapp-network
    restart: always

networks:
  socialapp-network:
    