name: build mern image and push to docker hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-back:
    name: server
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: zubairsource/mern_server
        dockerfile: server/Dockerfile
        tags: latest
  build-and-deploy-front:
    name: client
    runs-on: ubuntu-latest
    needs: build-and-deploy-back
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: zubairsource/mern_client
        dockerfile: client/Dockerfile
        tags: latest
  build-and-deploy-nginx:
    name: nginx
    runs-on: ubuntu-latest
    needs: build-and-deploy-front
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: zubairsource/mern_nginx
        dockerfile: nginx/Dockerfile
        tags: latest